const CONFIG = {
    titleWeb: "hello cậu <3",
    introTitle: 'Nguyễn Vũ Bảo Anh',
    introDesc: `cậu trả lời cho tớ mấy câu này nha ><`,
    btnIntro: 'okiiiii',
    title: 'làm người yêu tớ nha XD',
    desc: 'xin đừng từ chối mờ ',
    btnYes: 'tớ đồng ý <3',
    btnNo: 'Không cậu ơi ',
    question: 'lí do cậu thích mình ?',
    btnReply: 'mình nói thật đó',
    reply: 'tớ thích tính cách của cậu hi hi',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'cậu hứa 8 năm sau chúng ta sẽ lại thích nhau nha :333.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://www.facebook.com/profile.php?id=100071311105112'
