const CONFIG = {
    titleWeb: "Tiêu đề web",
    introTitle: 'Bảo Anh',
    introDesc: `trả lời cho mình vài câu hỏi nha`,
    btnIntro: 'okiiii',
    title: 'làm ny mình nha',
    desc: 'đừng ừ chối mờ ',
    btnYes: 'mình đồng ý',
    btnNo: 'Không nha :3',
    question: 'Trên thế giới hơn 7 tỉ người mà sao bạn lại yêu mình <3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'vì bạn đẹp trai học giỏi vv',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: '8 năm sau vẫn nhớ tới mình nha.',
    btnAccept: 'đương nhiên rùi',
    messLink: 'https://github.com/zukahai/Confess-Crush' 
